### ISSUE TITLE
Optim API

### ISSUE THREAD

**Issue by pkofod** [RedPointyJackson/Fitotron.jl#1]
Hi there!

Just browsing, as I saw you filed an issue over at Optim, so I was curious as to what you were using it for.

Allow me to recommend that you change the following lines
https://github.com/RedPointyJackson/Fitotron/blob/master/src/functions.jl#L38
https://github.com/RedPointyJackson/Fitotron/blob/master/src/functions.jl#L44
to use the `Optim.minimizer(res)` function instead of `.minimum`, and the following
https://github.com/RedPointyJackson/Fitotron/blob/master/src/functions.jl#L57
https://github.com/RedPointyJackson/Fitotron/blob/master/src/functions.jl#L70
to use the `Optim.minimum(res)` function instead of `.f_minimum`.

The older direct field access way of accessing results is no longer recommended, and the field names might change. As this cannot be deprecated, you won't know why you suddenly get an error, other than the error saying the field name does not exist. See http://www.juliaopt.org/Optim.jl/latest/user/minimization/#obtaining-results for all the functions in the new API.

Good luck with the package :)

**Comment by RedPointyJackson** [comment]
Thank you! I will use that syntax.
